name: Android APK Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - uses: actions/checkout@v4
    
    # 设置 JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # 赋予 gradlew 执行权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 构建 APK
    - name: Build APK
      run: ./gradlew assembleRelease

    # 保存 APK 文件为工件
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    # 检出代码
    - uses: actions/checkout@v4

    # 从上一步中下载 APK 工件
    - name: Download APK artifact
      uses: actions/download-artifact@v3
      with:
        name: app-release-apk

    # 发布到 GitHub Releases
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "Release ${{ github.run_number }}"
        draft: false
        prerelease: false
        files: app-release.apk
